### ISSUE TITLE
Add a quickstart example in the Readme 

### ISSUE THREAD

**Issue by AmgadHasan** [BrainBlend-AI/atomic-agents#12]
Hi,
Thanks for this amazing project.
I understand that creating and maintaining docs is extremely time consuming.

However, having at least one complete quick start example right in the Readme is quite important.

Requiring new users to open a jupyter notebook on github is an unnecessary step.

Thanks

**Comment by KennyVaneetvelde** [comment]
Done, feel free to make a PR for any desired improvements in the future!
