### ISSUE TITLE
SearxNGTool limit search to one domain

### ISSUE THREAD

**Issue by ilanb** [BrainBlend-AI/atomic-agents#16]
Hi, 
First, thanks for atomic-agents :-) work nice for me for now.
I try demo product finder and try to restrict domain search like :

`searxng_tool = SearxNGTool(SearxNGToolConfig(
    base_url=os.getenv("SEARXNG_BASE_URL"),
    max_results=5,
    search_params={
        "engines": "google",
        "language": "fr",
        "safesearch": 0,
        "site": "https://www.valrhona.com"
    }
))`

I modified agent prompt too but some responses go outside of the domain I mention 
How can I limit search and response to a single domain ? 

Thanks !
Ilan

**Comment by KennyVaneetvelde** [comment]
Hello,

We are currently reworking the way tools are distributed. We will be ripping them out of this package and providing them in a different way where you can take full ownership over the tool's code.

So, for now I will leave this issue open as it does look like it might be a bug in the tool (or maybe just missing functionality) but it won't be fixed anymore in this repository, but in the upcoming new one

Thanks for logging it!

**Comment by ilanb** [comment]
Hello thanks Kenny, 
Great news, Anyway, I resolved my problem and found interesting way to use it... 

I'll be following the development of atomic-agents !

**Comment by fayzfi** [comment]
Hi!
Do you have any timeline for reworking the tools?

**Comment by KennyVaneetvelde** [comment]
@fayzfi Should be max. another week to be usable. The CLI I am creating to get the tools is 90% done but I want to make sure we have a really good end-to-end getting-started guide as this introduces more "moving parts" so to speak.

**Comment by KennyVaneetvelde** [comment]
Well, the CLI is there, tools have been migrated, and everything is now ready for people to take ownership over the tools and modify to their hearts' content. Closing the issue!
