### ISSUE TITLE
Error when using ollama provider

### ISSUE THREAD

**Issue by lcalmbach** [BrainBlend-AI/atomic-agents#18]
this package looks very promising! thanks you for this important contribution! 

I try to use the custom-providers example and am having difficulties getting ollama to work. I have ollama installed locally and it works.

if I chose the ollama provider, I get this error: 
File "/home/lcalm/Work/Dev/weather-forecast/.venv/lib/python3.12/site-packages/instructor/retry.py", line 227, in retry_sync
    raise InstructorRetryException(
instructor.exceptions.InstructorRetryException: Error code: 400 - {'error': {'message': 'gemma:2b does not support tools', 'type': 'api_error', 'param': None, 'code': None}}

the python code looks like so, I have tried various models installed on my machine, always with the same error message, even if I enter a random string.
elif provider == "ollama":
        from openai import OpenAI as OllamaClient

        client = instructor.from_openai(OllamaClient(base_url="http://localhost:11434/v1", api_key="ollama"))
        model = "llama3:latest"
        
Any idea what could be wrong? any help will be greatly appreciated.

**Comment by KennyVaneetvelde** [comment]
Heya, looking at the error message, this seems to be a limitation of the gemma model within ollama, but I believe you can fix it by setting the mode to JSON

Give this a shot and let me know how that works out:

`client = instructor.from_openai(OllamaClient(base_url="http://localhost:11434/v1", api_key="ollama"), mode=instructor.Mode.JSON)`

**Comment by lcalmbach** [comment]
This worked like a charm, thank you very much.
