### ISSUE TITLE
using Azure OpenAI instead

### ISSUE THREAD

**Issue by dcsolus** [BrainBlend-AI/atomic-agents#21]
Thanks for the project. I was wondering if I could replace OpenAI client with Azure OpenAI? These two seems similar but different in some ways.

**Comment by KennyVaneetvelde** [comment]
It should certainly be possible!

Interfacing with these services and models is 100% through Instructor, and thus it should just be OpenAI's library that you can use... I don't have an Azure to test it with right now, but I would assume it would come down to just changing the base_url, and MAYBE play with the `mode`

```python
client = instructor.from_openai(
    openai.OpenAI(
        api_key=[API_KEY], 
        base_url=[AZURE_INSTANCE_BASE_URL],
        mode=instructor.Mode.JSON # this is also needed for some local ollama models, but try without first
    )
)

agent = BaseAgent(
    config=BaseAgentConfig(
        client=client,
        model="YOUR_MODEL",
    )
)
```

Please let me know if you have any specific difficulty trying this out our get any specific errors and be sure to check out the Instructor docs as well https://python.useinstructor.com/

Hope that helps!

**Comment by KennyVaneetvelde** [comment]
UPDATE:

I had some time to test it myself, and look it up properly.

The way to go is this:

`from openai import AzureOpenAI

client = instructor.from_openai(
    AzureOpenAI(
        api_key=os.getenv("AZURE_OPENAI_API_KEY"),
        azure_endpoint=os.getenv("AZURE_OPENAI_API_BASE"),
        api_version="2024-10-01-preview"
    )
)`

**Comment by dcsolus** [comment]
super thanks for a quick and thoughtful reply!
