### ISSUE TITLE
Examples under atomic-examples not working with ollama

### ISSUE THREAD

**Issue by ieea** [BrainBlend-AI/atomic-agents#32]
Hi,
I am trying to execute the examples provided under the aromic-example directory, by changing the models to Ollama (llama3.2/Granite) but i am getting the following error. Please support how to resolve the error.

**Error: Instructor does not support multiple tool calls, use List[Model] instead**

Regards,
Gaurav

**Comment by KennyVaneetvelde** [comment]
Hello,

Someone else recently had (and, before I could get to it, solved) this same issue.

Have a look here: https://github.com/BrainBlend-AI/atomic-agents/issues/30
