### ISSUE TITLE
Incorrect typing on BaseAgent.run()'s user_input?

### ISSUE THREAD

**Issue by mcrawford-fms** [BrainBlend-AI/atomic-agents#37]
Opening an issue rather than making a PR because I haven't used Python in 10+ years, so I'm blindly following Copilot and don't know how big the blast radius of this change might be.

Given code like:

```python
agent = BaseAgent(config=BaseAgentConfig())
agent.run(BaseAgentInputSchema(chat_message="..."))
```

I get a warning "Expected type 'Type[BaseIOSchema] | None', got 'BaseAgentInputSchema' instead."  Copilot suggests that in order to fix this warning the signature of the method should be `def run(self, user_input: Optional[BaseIOSchema] = None) -> BaseIOSchema`.

https://github.com/BrainBlend-AI/atomic-agents/blob/582f5ba15fe8d16018e85540374ce7033ceeb1bd/atomic-agents/atomic_agents/agents/base_agent.py#L157

**Comment by KennyVaneetvelde** [comment]
@mcrawford-fms that is a good catch!

May I ask what IDE you are using or any other kind of setup? Somehow this completely slipped by me in VSCode and since you are the first to mention this, I imagine it slipped by a lot of people

**Comment by mcrawford-fms** [comment]
@KennyVaneetvelde I'm using PyCharm.  Thanks for the fix!
