### ISSUE TITLE
Async Instructor Error

### ISSUE THREAD

**Issue by Sravan-k-DEV** [BrainBlend-AI/atomic-agents#42]
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Message
content
  Input should be a valid dictionary or instance of BaseIOSchema [type=model_type, input_value=<coroutine object AsyncIn...reate at 0x7fb26162a200>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.9/v/model_type
sys:1: RuntimeWarning: coroutine 'AsyncInstructor.create' was never awaited
```

This is the error I'm encountering while executing the Web-Search-Agent example. I'm being able to run the searxng_search.py file seperately and successffuly fetch the data by creating a local instance of searxng. But when I'm running the main file it isn't. i didn't change much of your code, you're core functionalities are same, just changed the client and model of the agent

**Comment by KennyVaneetvelde** [comment]
@Sravan-k-DEV Can you attach the relevant code snippet please? On first sight, it sounds to me like you should use the Async client of whatever  provider you are using... This is in the docs of Instructor itself, see: https://python.useinstructor.com/blog/2023/11/13/learn-async/?h=async

But beside `openai.OpenAI -> openai.AsyncOpenAI` there is also for example `groq.Groq -> groq.AsyncGroq`

If you provider doesn't have an async version, it might be best to fall back to the regular client and change any `run_async()` to `run()`

**Comment by Sravan-k-DEV** [comment]
Hi @KennyVaneetvelde, first of fall thanks for you're assistance.
The code is exactly the same. I haven't changed much except the agent.
```
agent = BaseAgent(
    config=BaseAgentConfig(
        client=instructor.from_openai(openai.AsyncAzureOpenAI(
            api_key=os.getenv("AZURE_OPENAI_API_KEY"),
            api_version=os.getenv("OPENAI_API_VERSION"),
            azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
        )),
        model="gpt-4o",
        memory=memory,
    )
)
```
As I took the subscription of Azure, currently I'm using that

**Comment by Sravan-k-DEV** [comment]
Besides i even tried with the gemini. but I'm not able to load the client.
```
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))
model = genai.GenerativeModel(model_name='models/gemini-pro')
client = instructor.from_gemini(model)

agent = BaseAgent(
    config=BaseAgentConfig(
        client=client,
        # model="gemini-pro",
        memory=memory,
    )
)
```
This is how i definied the gemini, I have commented the model because I'm getting this error
```
  File "/home/sravankumar/My_projects/Exploring_Atomic_Agents/.venv/lib/python3.12/site-packages/instructor/process_response.py", line 470, in handle_gemini_tools
    assert (
AssertionError: Gemini `model` must be set while patching the client, not passed as a parameter to the create method
```
After seeing this error I tried to uncomment it, but still the error doesn't go.

Thanks for you're time.

**Comment by Typepluto** [comment]
Hi @Sravan-k-DEV 
Just met same Gemini issue and found a workaround to fix it.

[/atomic_agents/agents/base_agent.py](https://github.com/BrainBlend-AI/atomic-agents/blob/main/atomic-agents/atomic_agents/agents/base_agent.py#L147)
Comment out line 149, 151, 152.
``` python
        response = self.client.chat.completions.create(
            messages=messages,
            # model=self.model,
            response_model=response_model,
            # temperature=self.temperature,
            # max_tokens=self.max_tokens,
        )
```

**Comment by KennyVaneetvelde** [comment]
@Typepluto Thank you for this

Since I don't use gemini, it's a bit hard to test for me, but I have labeled this in case anyone wants to pick it up and make a PR.

I suppose what it will come down to is adding some checks on which provider is being used and based on that, (don't) pass in properties of course gemini might have other ways to change the model, temperature, or max tokens, so we'll need to keep that into account.

For reference to whoever picks this up, proper usage can be found in https://github.com/instructor-ai/instructor

**Comment by Sravan-k-DEV** [comment]
@Typepluto @KennyVaneetvelde Thank you for your time,

after constant debugging and searching, even i found a way to achieve this,

*Google*

```
from google import generativeai as genai
from googleapiclient._auth import HAS_GOOGLE_AUTH

genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))
model = genai.GenerativeModel(model_name='models/gemini-pro')
client = instructor.from_gemini(HAS_GOOGLE_AUTH(api_key=api_key))
# client = Instructor(client=gemini, mode=instructor.Mode.JSON) # Use this if above is not working

agent = BaseAgent(
    config=BaseAgentConfig(
        client=client,
        model=model,
        memory=memory,
    )
)
```

*AzureOpenAI*

Here just remove the Async
```
agent = BaseAgent(
    config=BaseAgentConfig(
        client=instructor.from_openai(openai.AzureOpenAI(
            api_key=os.getenv("AZURE_OPENAI_API_KEY"),
            api_version=os.getenv("OPENAI_API_VERSION"),
            azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
        )),
        model="gpt-4o",
        memory=memory,
    )
)
```

**Comment by KennyVaneetvelde** [comment]
@Sravan-k-DEV @Typepluto 

Google has since released an OpenAI-compatible API for Gemini: https://ai.google.dev/gemini-api/docs/openai

An example, demonstrating it working with the latest Gemini 2.0 has been added to https://github.com/BrainBlend-AI/atomic-agents/blob/main/atomic-examples/quickstart/quickstart/4_basic_chatbot_different_providers.py

But here is a small standalone example to demo it working:

```python
import instructor
import os

from dotenv import load_dotenv
from openai import OpenAI

from atomic_agents.agents.base_agent import (
    BaseAgent,
    BaseAgentConfig,
    BaseAgentInputSchema,
)

load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    raise ValueError("GEMINI_API_KEY not found in environment variables.")

client = instructor.from_openai(
    OpenAI(api_key=api_key, base_url="https://generativelanguage.googleapis.com/v1beta/openai/"),
    mode=instructor.Mode.JSON,
)
model = "gemini-2.0-flash-exp"

# Agent setup with specified configuration
agent = BaseAgent(config=BaseAgentConfig(client=client, model=model, max_tokens=2048))

# Example conversation turn
user_input = "Hello, what can you do?"
input_schema = BaseAgentInputSchema(chat_message=user_input)
response = agent.run(input_schema)

print(f"Agent says: {response.chat_message}")
```

In light of this and since no code changes to the core framework code were necessary, I'll close this for now.
