### ISSUE TITLE
[Info] Develop a Multi-Agent RAG System based on Graphs

### ISSUE THREAD

**Issue by gianx89** [BrainBlend-AI/atomic-agents#43]
## Question: Multi-Agent RAG System Based on Graphs

Hi,

Is it possible to create a Multi-Agent RAG (Retrieval-Augmented Generation) system based on graphs? I want to define the agents, specify how they communicate through a graph, and start the chat until an agreement is reached.

Currently, I am implementing this using **Autogen**, and I’d like to understand how to achieve it using **atomic-agents**. Specifically, I am using features like:

- `speaker_selection_method`
- `allowed_or_disallowed_speaker_transitions`

Could you please provide some code examples if possible?

Thank you!

**Comment by KennyVaneetvelde** [comment]
I have thought about this in the past, I made a note to explore a library called "Burr" - but I have not yet had time to play around with it or thoroughly think about how integrated I want it to be within Atomic Agents, or maybe as a layer around it or, ..., as there are many use cases where going the graph/DAG-route would cause additional overhead and inflexibility (especially when heavily interspersing AI agents with traditional code, where you are treating AI agents as just another function albeit one that does something more advanced than other functions)

I am not too familiar with AutoGen anymore, but from what I can read, you should be able to do any of the speaker selection/transition stuff using Unions

You can use this example, but replace tool schemas with the schemas of other agents:
https://github.com/BrainBlend-AI/atomic-agents/blob/main/atomic-examples/orchestration-agent/orchestration_agent/orchestrator.py

Note, however, that from a practical use case point of view, I have not found much use in this yet as it tends to go off the rails quite a bit with hallucinations etc..

What is your use case if I may ask?

**Comment by gianx89** [comment]
I'm developing a system that can write a Comic Book Story with a specific format. There is writer or team of writers that writes the story, a critic or a team of critics that gives advices on how to improve the story a manager or team of managers that incorporates this suggestions. When the story is deemed satisfactory, an agent writes "TERMINATE".

Using Autogen and those 2 features, I can create transitions between agents based on a graph or something similar to it.

**Comment by KennyVaneetvelde** [comment]
Ahh I see,

Well, no reason why you can't simply do that with Unions & a good system prompt, the termination condition could just be a boolean in the output schema of the critic agent `is_story_satisfactory` or something like that.

But, I'd like to say though, I think this anthropomorphic way of thinking of agents is suboptimal and often detrimental to the final result.

What I would do is: Create a single writer agent, and a single critic agent. The writer's input schema is simply "input (str)" - though of course it can be anything you like
The critic's output schema is simply `feedback` and `is_story_satisfactory`

You start with the input to the writer being the user's request, and then you do a loop while `is_story_satisfactory` returns `false`, you:
- Pass the writer's output to the critic
- Pass the critic's output back to the writer

The only variant I'd think of trying out would be multiple writers and a critic, where the critic's output schema / prompting is then modified to output the best of the X writers and output feedback for that, back into all of the writers (but the writers don't need to communicate with each other, you are essentially creating a Tree-of-Thoughts-like setup...

Anyway yeah, I really recommend trying to step away from the "anthropomorphic" view of agents where you think of them as roles people would usually take or do tasks in exactly the way humans or human teams would - it'll usually only end up making the output worse and make it more costly to generate

I'll close the issue for now so as to not go off-topic too much here - but I'll definitely look into integrating a more DAG-based approach to piping agents together at some point as it is on my own wishlist as well, granted that it is useful enough and not implemented in a way that is detrimental to the developer experience in any way
