### ISSUE TITLE
Issue in deep research example

### ISSUE THREAD

**Issue by ieea** [BrainBlend-AI/atomic-agents#44]
Hi,
I was trying to execute deep-research example. I am getting following error.

"Current Python version (3.12.3) is not allowed by the project (^3.13)."
But the pyproject.toml at the base directory level i.e. atomic agents directory 'python = ">=3.11,<4.0"' is specified, so shall I upgrade python ?

**Comment by KennyVaneetvelde** [comment]
This has since been fixed! The min. python version is now 3.11
