### ISSUE TITLE
Integrating Anthropic Vision or any other AI for image analysis

### ISSUE THREAD

**Issue by herryelbert** [BrainBlend-AI/atomic-agents#48]
Hi, I'm new to this AI thing. I'm trying to implement a system for analyzing image to the Atomic Agent system for my LLM. Is there a way to do that? I tried adding Anthropic Vision externally, but the problem is that the Atomic Agent doesn't have the resource for the image so if I ask the LLM to re-analyze it, it doesn't work. Any help would be greatly appreciated. Thanks.

**Comment by KennyVaneetvelde** [comment]
Hi, I'm currently working on a separate branch on enabling vision models - Instructor already supports it, I am just trying to make it as developer-friendly as possible.

I am expecting this to be done soon (as in the coming days), including an example where we extract nutrition data from images which should help you along

Currently I can only test it with OpenAI's models but I will reference this ticket and tag you when it's done so you can have a test!

**Comment by herryelbert** [comment]
Hi Kenny, thank you so much for the reply. Can't wait to test it when it's up :)

**Comment by KennyVaneetvelde** [comment]
@herryelbert https://github.com/BrainBlend-AI/atomic-agents/tree/main/atomic-examples/basic-multimodal

Have a go with this! I tested it both with OpenAI and Gemini, but as I don't have access to Anthropic I did not manage to test that, but I don't see why it shouldn't work if it does for OpenAI and Gemini. Let me know if it does not work, though!

**Comment by KennyVaneetvelde** [comment]
I'll close the issue for now since it's been released

**Comment by herryelbert** [comment]
Thanks a lot Kenny
